### ISSUE TITLE
- Set default TFAR frequencies

### ISSUE THREAD

**Issue by bmrgit** [bmrgit/-BMR-KP-Liberation#2]

**Comment by Truckerpreben** [comment]
Currently waiting for help form tfar discord. 
as the side radio modul should set default freqs to the whole side
but it dosent.. 

so waiting for response from tfar discord on how to set it up correctly

**Comment by Truckerpreben** [comment]
according to dedman(dev) on tfar discord the 0.9 modules har unstable. and properly wont work. so im parking this task

**Comment by Truckerpreben** [comment]
Update:
I chatted with the dedman from tfar discord, who told me the beta version works
i tested it out and it sure dos, you can either change the setting in group attributes in 3DEN or via cba settings.
